name: Swift

on:
  push:
    branches: [ master, features/markers ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14"
    - name: Run tests
      run: swift test -v -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14"
